/*============================================================================
Copyright 2017 Koichi Murakami

Distributed under the OSI-approved BSD License (the "License");
see accompanying file LICENSE for details.

This software is distributed WITHOUT ANY WARRANTY; without even the
implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the License for more information.
============================================================================*/
#ifndef MEDICAL_BEAM_H
#define MEDICAL_BEAM_H

#include "G4VUserPrimaryGeneratorAction.hh"

#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
  TypeName(const TypeName&);               \
  void operator=(const TypeName&)

class G4ParticleDefinition;

class MedicalBeam : public G4VUserPrimaryGeneratorAction {
public:
  MedicalBeam();
  ~MedicalBeam();

  enum { kElectron = 0, kPhoton };

  void SetParticle(int ptype);
  int GetParticle() const;

  void SetElectronEnergy(double energy);
  double GetElectronEnergy() const;

  // distruubuted energy spectrum generated by specified MV electron (6/18 MV)
  void SetPhotonVoltage(int volt);
  int GetPhotonVoltage() const;

  void SetSSD(double val_ssd);
  double GetSSD() const;

  void SetFieldSize(double val_xy);
  double GetFieldSize() const;

  virtual void GeneratePrimaries(G4Event* event);

private:
  DISALLOW_COPY_AND_ASSIGN(MedicalBeam);

  int particle_type_;
  double electron_energy_;
  int photon_voltage_;

  double ssd_;
  double field_xy_;
};

// ====================================================================
inline void MedicalBeam::SetParticle(int ptype)
{
  particle_type_ = ptype;
}

inline int MedicalBeam::GetParticle() const
{
  return particle_type_;
}

inline void MedicalBeam::SetElectronEnergy(double energy)
{
  electron_energy_ = energy;
}

inline double MedicalBeam::GetElectronEnergy() const
{
  return electron_energy_;
}

inline int MedicalBeam::GetPhotonVoltage() const
{
  return photon_voltage_;
}

inline void MedicalBeam::SetSSD(double val_ssd)
{
  ssd_ = val_ssd;
}

inline double MedicalBeam::GetSSD() const
{
  return ssd_;
}

inline void MedicalBeam::SetFieldSize(double val_xy)
{
  field_xy_ = val_xy;
}

inline double MedicalBeam::GetFieldSize() const
{
  return field_xy_;
}

#endif
