# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
jobs:
  ecal_107:
    docker:
      - image: koichimurakamik6/geant4-runtime:10.7.3
    working_directory: ~/work/g4bench
    environment:
      - NOG4VERSION: "1"

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: test_ecal
          command: |
            echo $NOG4VERSION
            ./tests/ci/test_ecal.sh

workflows:
  build_and_run:
    jobs:
      - ecal_107
