#
# set environment vars for data files
#

export G4ABLADATA=$G4DATA/G4ABLA3.1
export G4LEDATA=$G4DATA/G4EMLOW7.3
export G4ENSDFSTATEDATA=$G4DATA/G4ENSDFSTATE2.2
export G4NEUTRONHPDATA=$G4DATA/G4NDL4.5
export G4NEUTRONXSDATA=$G4DATA/G4NEUTRONXS1.4
export G4PIIDATA=$G4DATA/G4PII1.3
export G4SAIDXSDATA=$G4DATA/G4SAIDDATA1.1
export G4LEVELGAMMADATA=$G4DATA/PhotonEvaporation5.2
export G4RADIOACTIVEDATA=$G4DATA/RadioactiveDecay5.2
export G4REALSURFACEDATA=$G4DATA/RealSurface2.1.1
